server:
  port: 7777

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka


spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          predicates:
            - Path=/service-optimization/**
          filters:
            - RewritePath=/service-optimization/(?<s>.*), /${s}
            #-  name: RequestRateLimiter
            #   args:
            #     redis-rate-limiter.replenishRate: 5   # Tokens added per second
            #     redis-rate-limiter.burstCapacity: 10  # Max number of requests allowed in a burst
            #     key-resolver: "#{@ordonnanceKeyResolver}"

          uri: lb://MS-OPTIMIZATION

        


  